services:
  web:
    build: .
    container_name: openclinic-web
    volumes:
      - ./:/var/www/html
      - php_sessions:/var/lib/php/sessions
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  db:
    image: mysql:5.7
    container_name: openclinic-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: openclinic
      MYSQL_USER: openclinic_user
      MYSQL_PASSWORD: openclinic_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: openclinic-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
  db_data:
  php_sessions: